[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "daily_git"
version = "0.1.0"
description = "A CLI tool to track your git stats daily"
authors = [
    { name = "Luca Bruno Knaack", email = "l.knaack93@gmail.com" }
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.7"
dependencies = [
    "rich",
    "GitPython"
]

[project.scripts]
daily-git = "daily_git.cli:main_cli"